# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gnome-software-3.26.1";

  src = fetchurl {
    url = mirror://gnome/sources/gnome-software/3.26/gnome-software-3.26.1.tar.xz;
    sha256 = "185d5dabe23788905dcd3c2b0c6dd7a8d5d5b753eab0adce194b5e82dbf3d3e5";
  };
}
