# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "nautilus-3.26.0";

  src = fetchurl {
    url = mirror://gnome/sources/nautilus/3.26/nautilus-3.26.0.tar.xz;
    sha256 = "a02b30ef9033f6f92fbc5e29abaceeb58ce6a600ed9fa5a4697ba82901d07924";
  };
}
